### ISSUE TITLE
Add type="module" attribute to the <script> tag

### ISSUE THREAD

**Issue by orsolyalukacs** [adrianmcli/nano-react-app#31]
After npm install and npm start, the app throws this error:

```Add the type="module" attribute to the <script> tag.```

I know this is because of [parcel is adding classic script](https://parceljs.org/languages/javascript/#classic-scripts)  and it can be easily fixed.
However, it would speed up the development process if the nano-react-app would be already implemented with type="module" in my opinion.

**Comment by mgreasly** [comment]
Hey - see the discussion on the build tool change in https://github.com/nano-react-app/nano-react-app/issues/29. This change isn't needed for Parcel now, but Vite needs it as well, so it's included in that PR.

**Comment by orsolyalukacs** [comment]
@mgreasly thank you, that's great! I look forward to it being merged.
